services:
  vector:
    image: timberio/vector:0.40.0-alpine
    container_name: ferm-vector
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
    restart: unless-stopped
