ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS yogurt_ml INT NOT NULL DEFAULT 0;

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS sunflower_oil_ml INT NOT NULL DEFAULT 0;

ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS salads_eaten INT NOT NULL DEFAULT 0;